[pytest]
addopts = --headed --slowmo 1200 --browser-channel chrome
base_url = https://www.igdb.com

markers =
    ui: UI Automation tests with Playwright browser
    api: Backend API tests without browser overhead
